# Generated by Django 3.0.7 on 2020-06-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200610_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='noOfAnswers',
            field=models.IntegerField(default=0),
        ),
    ]
