# Generated by Django 3.0.7 on 2020-06-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20200611_0618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='answer_id',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='question_id',
            new_name='question',
        ),
    ]
